@startuml C4 Context User API
title C4 Context User API

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LEFT_RIGHT()

UpdateElementStyle(person, $bgColor="#2b4a74ff")
UpdateElementStyle(system, $bgColor="#4373b1ff")
UpdateElementStyle(external_system, $bgColor="#96b6beff")
UpdateElementStyle(boundary, $bgColor="#d1dcdfff")

Person(user, "User")

Boundary(frontend, "RMO Frontend") {
    System_Ext(rmu_fe_host, "RMO Frontend Host", "Node.js / JS")
}

Boundary(apis, "RMO APIs") {
    System(rmu_api_users, "Users API", "NestJS")
}

Boundary(infrastructure, "Infrastructure") {
    System_Ext(mongodb, "MongoDB", "")
    System_Ext(keycloak, "Keycloak", "26.3")
    System_Ext(kafka, "Kafka", "")
}

Rel(user, rmu_fe_host, "Navigate", "HTTP")
Rel(user, keycloak, "Login", "HTTP")

Rel(rmu_fe_host, rmu_api_users, "API Requests", "HTTP")

Rel(rmu_api_users, keycloak, "Query users, read JWK and request tokens", "HTTP")

Rel(rmu_api_users, mongodb, "Read/Write user data", "mongoose")

Rel(rmu_api_users, kafka, "Produce / Consume events", "Kafka")

SHOW_LEGEND()

@enduml
